Homework2
ohthatbaguk/QA_Lab pull request #2
Opened 2021-02-16 18:13 UTC by ohthatbaguk

2021-02-16 19:06 UTC, mashadolya requested changes

2021-02-16 19:06 UTC, mashadolya commented on Homework2/Program.cs
> +           var employees = factory.GetEmployees(new Faker().Random.Int(1, 4));
Избегаем магичекие числа, буквы и любые другие данные
создаем константы типа `const minUserCount = 1` и  `const maxUserCount = 4`

2021-02-18 12:05 UTC, Maria-Dolia requested changes
1. Code convention 
2. Удалить неиспользуемые конструкторы
3. Исправить репорт генераторы

2021-02-18 12:05 UTC, Maria-Dolia commented on Homework2/Report/EmployeeReportGenerator.cs
> +            var emp = factory.GetEmployees(new Faker().Random.Int(minUserCount, maxUserCount));
нам не нужно создавать тут новых юзеров, нам нужно их передать из мейна , мы же там уже нагенерили их
А репорт генератор просто выводит информацию о них с заданной сортировкой

2021-02-19 07:33 UTC, mashadolya requested changes

2021-02-19 07:33 UTC, mashadolya commented on Homework2/Program.cs
> +            var empRep = new EmployeeReportGenerator();
Сокращения в нейминге переменных считается бэд практис
Используй что то типа `var employeesReportGenerator = ...`

2021-02-19 07:33 UTC, mashadolya commented on Homework2/Models/Job.cs
> +    {
лишняя пустая строка

2021-02-19 07:36 UTC, mashadolya approved these changes

2021-02-23 21:32 UTC, merged