homework4
ohthatbaguk/QA_Lab pull request #6
Opened 2021-03-02 18:57 UTC by ohthatbaguk

2021-03-03 10:13 UTC, olgayuks commented on Homework_4/Menu/ShopHelper.cs
> +
здесь я бы поставила модификатор доступа

2021-03-03 10:13 UTC, olgayuks commented on Homework_4/Models/Phone.cs
> +}
не хватает отступов

2021-03-03 10:15 UTC, olgayuks commented on Homework_4/Menu/ShopHelper.cs
> +
сообщения исключений лучше заканчивать точкой

2021-03-03 10:48 UTC, mashadolya requested changes
1. `Enums `храним в директории `Models `и нейминг в PascalCase
2. `Menu `переименовать, н-р, `Helpers`
3. Папка `JSON` тоже непонятна.....

2021-03-03 10:48 UTC, mashadolya commented on Homework_4/JSON/ExtendedJsonReader.cs
> +                pathToFile = File.ReadAllText("appsettings.json");
а можем имя файла передавать в метод, чтобы можно было читать любые джсон файла, а не только аппсеттингс?

2021-03-03 10:48 UTC, mashadolya commented on Homework_4/JSON/ExtendedJsonReader.cs
> +            string pathToFile = default;
var pathToFile  = string.Empty

2021-03-03 10:48 UTC, mashadolya commented on Homework_4/JSON/ExtendedJsonReader.cs
> +            string pathToFile = default;
И это же не путь к файлу

2021-03-03 10:48 UTC, mashadolya commented on Homework_4/Menu/ShopHelper.cs
> +        public static int GetPhonesByOperationSystem(Shop shop, OperationSystemType op)
не `op`, а полное название переменной)

2021-03-03 10:48 UTC, mashadolya commented on Homework_4/Menu/ShopHelper.cs
> +            List<Phone> listOfPhones = new List<Phone>();
я бы назвала `foundedPhones`

2021-03-03 10:48 UTC, mashadolya commented on Homework_4/Menu/ShopHelper.cs
> +                    Logger.Error("This product is out of stock. Please choose another model. ");
и что в каждом кетче  `PhoneNotAvailableException ` будем прописывать сообщение исключения?

2021-03-03 10:48 UTC, mashadolya commented on Homework_4/Menu/ShopHelper.cs
> +                    break;
по код конвеншенам мы должны всегда ставить {} даже в самых примитивных выражениях

2021-03-03 10:48 UTC, mashadolya commented on Homework_4/Menu/ShopHelper.cs
> +                        throw new PhoneNotAvailableException();
вот тута как раз таки и можно было бы опеределить errorMessage для Exception

2021-03-03 10:48 UTC, mashadolya commented on Homework_4/Program.cs
> +            var stores = JsonConvert.DeserializeObject<Stores>(ExtendedJsonReader.ReadFile());
что будем делать , если не смапит в Stores?

2021-03-09 13:21 UTC, Maria-Dolia approved these changes

2021-03-09 13:21 UTC, Maria-Dolia commented on Homework_4/Exceptions/PhoneNotAvailableException.cs
> +            LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
нужно это?

2021-03-09 13:21 UTC, Maria-Dolia commented on Homework_4/Exceptions/PhoneNotFoundException.cs
> +        public PhoneNotFoundException(string message, Exception inner) : base(message,inner)
отступы))

2021-03-09 13:21 UTC, Maria-Dolia commented on Homework_4/Helpers/ShopHelper.cs
> +                        throw new PhoneNotAvailableException();
укажи тут сообщение об ошибке а в кетч ты будешь делать не `Log.Error("Smthg is wrong")`, а `Log.Error(ex.GetMessage())`

2021-03-09 13:21 UTC, Maria-Dolia commented on Homework_4/Helpers/ShopHelper.cs
> +                throw new PhoneNotFoundException();
code convention

2021-03-09 20:28 UTC, merged